---
- name: Deploy mongodb
  hosts: mongo
  become: yes
  roles:
    - role: mongodb
      state: started
  tags:
    - mongo

- name: Deploy rabbitmq
  hosts: rabbitmq
  become: yes
  roles:
    - role: rabbitmq
      state: started
  tags:
    - romanesco
    - cumulus

- name: Deploy girder
  hosts: girder
  become: yes
  vars:
    girder_venv_root: "/opt/girder/libs"
  roles:
    - role: girder
      mongodb_ansible_group: mongo
#      girder_version: "v1.4.1"
      girder_version: "master"
      state: started

    - role: romanesco
      rabbitmq_ansible_group: rabbitmq
      romanesco_version: "cfdc285fd2d94"
      do_install_girder: true
      state: started
      tags:
        - romanesco

    - role: cumulus
      cumulus_version: "ansible-refactor"
      do_girder_install: true
      state: started
      tags:
        - cumulus

    - role: minerva
      state: started
      minerva_version: "cumulus-frontend-integration"
      tags:
        - minerva

  tasks:
    - name: cumulus_frontend | install | plugin
      shell: >
        . {{ girder_venv_root }}/bin/activate
        girder-install plugin -s -f {{ minerva_install_root }}/plugins/cumulus_frontend
      become: yes
      become_user: girder
      tags:
        - config


- name: Configure girder
  hosts: girder
  tags:
    - config
  tasks:
    - name: Install girder client
      pip:
        name: girder-client
        version: 1.1.1
      become: yes
      become_user: root

    - name: Create 'admin' User
      girder:
        host: "{{ ansible_default_ipv4['address'] }}"
        port: 9080
        user:
          firstName: "Admin"
          lastName: "User"
          login: "admin"
          password: "letmein"
          email: "admin.user@kitware.com"
          admin: yes
        state: present

    - name: Create 'cumulus' User
      girder:
        host: "{{ ansible_default_ipv4['address'] }}"
        port: 9080
        username: "admin"
        password: "letmein"
        user:
          firstName: "Cumulus"
          lastName: "Cumulus"
          login: "cumulus"
          password: "letmein"
          email: "cumulus@kitware.com"
        state: present

    - name: Create cumulus group with cumulus user
      girder:
        host: "{{ ansible_default_ipv4['address'] }}"
        port: 9080
        username: "admin"
        password: "letmein"
        group:
          name: "cumulus"
          description: "cumulus group"
          users:
            - login: cumulus
              type: admin
        state: present

    - name: Create filesystem assetstore
      girder:
        host: "{{ ansible_default_ipv4['address'] }}"
        port: 9080
        username: "admin"
        password: "letmein"
        assetstore:
          name: "Filesystem Assetstore"
          type: "filesystem"
          root: "/data/girder"
          current: true
        state: present

    - name: Ensure minerva, cumulus, romanesco and cumulus_frontend plugins are enabled
      girder:
        host: "{{ ansible_default_ipv4['address'] }}"
        port: 9080
        username: "admin"
        password: "letmein"
        plugins:
          - minerva
          - cumulus
          - cumulus_frontend
          - romanesco
        state: present

    - name: Restart the server
      girder:
        host: "{{ ansible_default_ipv4['address'] }}"
        port: 9080
        username: "admin"
        password: "letmein"
        put:
          path: "system/restart"
