domain: "cluster.dev"
ansible:
  verbose: ""
  plays:
    - playbook: "../gobig/playbooks/hadoop-hdfs/site.yml"
    - playbook: "../gobig/playbooks/spark-standalone/site-custom-hdfs.yml"
    - playbook: "local.yml"
nodes:
  head:
    memory: 8192
    cpus: 4
    mount:
      - src: ../../
        dest: /home/vagrant/NEX
      - src: /data/NEX-GDDP-1997/
        dest: /data/tmp
    roles:
      - head
      - namenodes
      - datanodes
      - spark
      - nex
  data-01:
    memory: 8192
    cpus: 4
    roles:
      - spark
      - datanodes
      - spark-slaves
      - nex
    mount:
      - src: /data/NEX-GDDP-1997/
        dest: /data/tmp

  data-02:
    memory: 8192
    cpus: 4
    roles:
      - spark
      - datanodes
      - spark-slaves
      - nex
    mount:
      - src: /data/NEX-GDDP-1997/
        dest: /data/tmp
