---

  - name: cumulus | install | girder virtualenv | python dependencies
    pip:
      requirements: "{{cumulus_install_root}}/requirements.txt"
      virtualenv: "{{ girder_venv_root }}"
    become: yes
    become_user: "{{ cumulus_plugin_user }}"

  - name: cumulus | install | girder virtualenv | cumulus
    pip:
      chdir: "{{ cumulus_install_root }}"
      name: "."
      extra_args: "-e"
      virtualenv: "{{ girder_venv_root }}"
    become: yes
    become_user: "{{ cumulus_plugin_user }}"

  - name: cumulus | plugin root | owner | set
    file:
      path: "{{ cumulus_plugin_root }}"
      state: directory
      group: "{{ cumulus_plugin_group }}"
      owner: "{{ cumulus_plugin_user }}"
    when: do_install|bool


  - name: cumulus | install | girder | plugin
    shell: ". {{ girder_venv_root }}/bin/activate && girder-install plugin -s -f {{ cumulus_plugin_root }}"
    become: yes
    become_user: "{{ cumulus_plugin_user }}"
