---
  - name: cumulus | install root | delete
    file:
      path: "{{ cumulus_install_root }}"
      state: absent
    when: remove_install_root|bool

  - name: cumulus | data root | delete
    file:
      path: "{{ cumulus_data_root }}"
      state: absent
    when: remove_data_root|bool

  - name: cumulus | install parent | create
    file:
      path: "{{ cumulus_install_parent }}"
      state: directory
    when: do_install|bool

  - name: cumulus | data root | create
    file:
      path: "{{ cumulus_data_root }}"
      state: directory
      group: "{{ celery_group }}"
      owner: "{{ celery_user }}"
      mode: 0755
    when: do_install|bool

  - name: cumulus | data root | create
    file:
      path: "{{ cumulus_keys_directory }}"
      state: directory
      group: "{{ celery_group }}"
      owner: "{{ celery_user }}"
      mode: 0700
    when: do_install|bool

  - name: cumulus | install root | create
    file:
      path: "{{ cumulus_install_root }}"
      state: directory
      group: "{{ celery_group }}"
      owner: "{{ celery_user }}"
      mode: 0755
    when: do_install|bool

  - name: cumulus | repo | sync
    command: >
        rsync -avz --exclude=.git
        "{{ cumulus_git_work_dir }}/"
        "{{ cumulus_install_root }}/"
    become: yes
    become_user: "{{ celery_user }}"
    when: do_install|bool


  - name: Get local host name, used in Vagrant deployment
    command: hostname --fqdn
    register: local_hostname

  - name: cumulus | create config.json
    template:
      src: config.json.j2
      dest: "{{cumulus_install_root}}/config/config.json"
      mode: 0640
      owner: "{{ celery_user }}"
      group: "{{ celery_group }}"

  - name: cumulus | install | python dependencies
    pip:
      requirements: "{{cumulus_install_root}}/requirements.txt"
    when: do_install|bool

  - name: cumulus | install | cumulus
    pip:
      chdir: "{{ cumulus_install_root }}"
      name: "."
      extra_args: "-e"

  - name: cumulus | set | egg | permissions
    file:
      path: "{{ cumulus_install_root }}"
      recurse: true
      state: directory
      owner: "{{ celery_user }}"
      group: "{{ cumulus_plugin_group }}"
      mode: g+w

  - name: cumulus | install | girder | plugin
    include: girder.yml
    when: do_girder_install|bool
