# The directory to download the spark distro into
# Should be an NFS directory so we don't have to do multiple
# downloads from cluster-external sources
spark_download_dir: /public

# The base directory where spark will live
spark_base_dir: /opt

# The version of spark to download
spark_version: 1.6.1

# spark's home directory
spark_home: "{{ spark_base_dir }}/spark/{{ spark_version }}"
spark_config: "{{ spark_home }}/conf"
