galaxy_info:
  author: Kitware, Inc.
  description: Install the Cumulus package and related Girder plugins
  company: Kitware, Inc.

  license: Apache
  min_ansible_version: 1.9

  platforms:
  - name: Ubuntu
    versions:
    - trusty

  galaxy_tags:
    - cumulus
    - girder


dependencies:
  - role: girder
