# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

require 'yaml'

Vagrant.configure(2) do |config|

  # The number of datanodes to launch
  # NODES=3

  config.vm.box = "ubuntu/trusty64"

  if File.exists?(File.dirname(__FILE__) + "/dev/vagrant.local.yml")
    nc = YAML.load_file(File.dirname(__FILE__) + "/dev/vagrant.local.yml")
  else
    nc = YAML.load_file(File.dirname(__FILE__) + "/dev/vagrant.dist.yml")
  end

  # Ensure nodes and ansible config sections exist
  nc['nodes'] ||= {}
  nc['ansible'] ||= {}

  # Set default domain
  domain = nc["domain"] || "cluster.dev"

  groups = {}
  host_vars = {}
  # Node index,  cannot use nc['nodes'].each_with_index because configs
  # are lazy loaded See: https://docs.vagrantup.com/v2/vagrantfile/tips.html
  i = 0
  # Loop over node definitions
  nc['nodes'].each do |name, params|

    # Add node to group roles
    params['roles'].each do |role|
      groups[role] ||= []
      groups[role] << name
    end

    # Make sure 'ports' config section is available
    params['ports'] ||= []

    config.vm.define name do |node|

      # Set port forwarding from ports
      params['ports'].each do |id, ports|
        guest, host = ports.split(":")
        node.vm.network :forwarded_port, guest: guest, host: host, id: id
      end

      host_vars[name] = {"private_ip": "192.168.33.2#{i}",
                         "fqdn": "#{name}.#{domain}" }

      node.vm.network :forwarded_port, guest: 22, host: 2220 + i, id: 'ssh'
      node.vm.network "private_network", ip: "192.168.33.2#{i}", netmask: "255.255.255.0"
      node.vm.hostname = "#{name}.#{domain}"
      node.vm.provider "virtualbox" do |vb|

        vb.memory = params["memory"] || 2048
        vb.cpus = params["cpus"] || 2

        if params.has_key?("mount")
          mount = params['mount']
          if mount.kind_of?(Array)
            mount.each do |mnt|
              config.vm.synced_folder mnt['src'], mnt['dest'], create: true
            end
          else
            config.vm.synced_folder mount['src'], mount['dest'], create: true
          end
        end
      end
      # Update node index
      i += 1

      # Only provision after all nodes have been spun up.
      if i == nc['nodes'].length
        groups['all:children'] = groups.keys

      # ap:  ansible paramaters
        ap = nc['ansible']

        # Ensure plays exists
        ap['plays'] ||= []

        # Loop through plays and run each provisioner
        ap['plays'].each do |play|
          node.vm.provision "ansible" do |ansible|
            ansible.groups = groups
            ansible.host_vars = host_vars
            ansible.limit = 'all'
            ansible.verbose = play['verbose'] || ap['verbose'] || nil
            ansible.playbook = play['playbook']
            ansible.extra_vars = {
              ansible_user: "vagrant",
              cluster_users: ["vagrant"],
              vpc_cidr: "192.168.33.0/24"
            }
          end
        end
      end
    end
  end
end
