# Modified from:
# https://github.com/gettyimages/docker-spark/blob/master/docker-compose.yml

master:
  build: .
  command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
#  command: /opt/spark/sbin/start-master.sh
  hostname: master
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_HOME: /opt/spark
    SPARK_DAEMON_MEMORY: 12g
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./conf/master:/conf
    - ./data:/data

worker:
  build: .
  command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 12g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
    SPARK_HOME: /opt/spark
    SPARK_DAEMON_MEMORY: 12g

  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081
  volumes:
    - ./conf/worker:/conf
    - ./data:/data