---
- name: "Generate a public/private key for {{ item }} user"
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  register: user_module_output
  become: yes
  become_user: root

- name: "Add authorized key to master for {{ item }}"
  authorized_key:
    user: "{{ item }}"
    key: "{{ user_module_output.ssh_public_key }}"
  become: yes
  become_user: root

- name: Set public key fact on master host
  set_fact:
    user_public_keys: "{{ user_public_keys|default({})|combine({ item: user_module_output.ssh_public_key }) }}"

- name: "Remove known_hosts"
  file:
    path: ~/.ssh/known_hosts
    state: absent
  tags:
    - update_configs
