---

  - hosts: localhost
    connection: local
    gather_facts: false
    become: false
    pre_tasks:
      - include: pod_config.yml
    roles:
      - role: ec2-pod
        default_ssh_key: "{{ ec2_pod_spec.key }}"
        name: kotfic_nex
        state: running
        region: us-west-2
        default_image: ami-e0f7e081
        ec2_instance_profile_name: NEX
        rules: "{{ ec2_pod_spec.rules }}"
        hosts: "{{ ec2_pod_spec.hosts }}"

    tags:
      - always
