---

  - hosts: localhost
    connection: local
    gather_facts: false
    become: false
    pre_tasks:
      - include: pod_config.yml
    roles:
      - role: ec2-pod
        default_ssh_key: "{{ ec2_pod_spec.key }}"
        name: nex
        state: running
        region: us-west-2
        default_image: ami-5189a661
        rules: "{{ ec2_pod_spec.rules }}"
        hosts: "{{ ec2_pod_spec.hosts }}"

    tags:
      - test
      - hdfs
      - spark