- include: instantiate.yml
- hosts: nex
  user: ubuntu
  tasks:
    - name: update bashrc
      lineinfile:
        dest: /home/ubuntu/.bashrc
        line: "{{ item }}"
      with_items:
        - "export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64"
        - "export HADOOP_HOME=/opt/hadoop/2.7.1"
        - "export HADOOP_VERSION=2.7.1"
        - "export HADOOP_CONF_DIR=/opt/hadoop/2.7.1/etc/hadoop/"

    - name: install tools
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - parallel
        - default-jdk
        - openjdk-7-source
        - python-pip
        - python-dev
        - python-numpy
        - htop
        - libhdf5-7
        - libhdf5-dev
        - libnetcdf-dev
        - netcdf-bin
        - git
        - libblas-dev
        - liblapack-dev
        - libatlas-base-dev
        - gfortran
      sudo: yes

    - name: install python packages
      pip:
        name: "{{ item }}"
      with_items:
        - pssh
        - netCDF4
        - xray
        - py4j
        - jupyter
        - ipython[notebook]
        - ipyparallel
        - avro
      sudo: yes

# Intermittent compile errors with pydoop
# Not currently using so not going to debug
#     - name: install pydoop
#       pip:
#         name: pydoop
#       environment:
#         JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64
#         HADOOP_HOME: /opt/hadoop/2.7.1
#         HADOOP_VERSION: 2.7.1
#         HADOOP_CONF_DIR: /opt/hadoop/2.7.1/etc/hadoop
#       sudo: yes

    - name: Add public ssh key to all hosts
      authorized_key:
        user: ubuntu
        key: "{{ lookup('file', '../keys/master.pub') }}"

    - name: Make a temporary directory in /data/
      file:
        path: /data/tmp/
        owner: ubuntu
        group: ubuntu
        state: directory
        mode: 0755
      sudo: yes

- hosts: head
  user: ubuntu
  tags:
    - local
  tasks:
    - name: generate ip.list
      local_action: command /home/kotfic/kitware/projects/NEX/aws/get_cluster_ips.sh

    - name: install tools
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - emacs24-nox
        - links
        - maven
        - libfreetype6-dev
        - libpng-dev
      sudo: yes

    - name: Get scala 2.11.4
      get_url:
        url: "http://downloads.typesafe.com/scala/2.11.4/scala-2.11.4.deb"
        dest: /home/ubuntu/src/



    - name: Install scala Deb
      apt:
        deb: /home/{{ ansible_env.USER }}/src/scala-2.11.4.deb
      sudo: true

    - name: Set up SBT source
      shell: "echo \"deb https://dl.bintray.com/sbt/debian /\" | sudo tee -a /etc/apt/sources.list.d/sbt.list"
      sudo: yes

    - name: Add SBT key
      shell: "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823"
      sudo: yes

    - name: Install SBT
      apt:
        name: sbt
        update-cache: yes
      sudo: yes

    - name: Setup ensime plugin
      lineinfile:
        line: "addSbtPlugin(\"org.ensime\" % \"ensime-sbt\" % \"0.2.1\")"
        dest: /home/ubuntu/.sbt/0.13/plugins/plugins.sbt
        create: yes

    - name: install python packages
      pip:
        name: "{{ item }}"
      with_items:
        - pssh
      sudo: yes

    - name: copy local files
      copy:
        src: "{{ item }}"
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0644
      with_items:
        - all_files.txt
        - 1997_files.txt
        - ip.list
        - all.sh

    - name: All is a script
      file:
        path: /home/ubuntu/all.sh
        mode: 0755

    - name: copy ssh config and private key
      copy:
        src: "{{ item }}"
        dest: /home/ubuntu/.ssh/
        owner: ubuntu
        group: ubuntu
        mode: 0600
      with_items:
        - ../keys/master
        - config

    - name: Add 1997_http_files
      shell: sed -e "s/s3n:\/\/nasanex\//http:\/\/nasanex.s3.amazonaws.com\//g" /home/ubuntu/1997_files.txt > /home/ubuntu/1997_http_files.txt


- hosts: head
  user: ubuntu
  roles:
    - role: pyspark_jupyter_notebook
  tasks:
    - name: Checkout git repo
      git:
        repo: git@github.com:OpenGeoscience/NEX.git
        accept_hostkey: True
        dest: ~/NEX/
        version: master
