---

- include: instantiate.yml
- include: filesystem.yml

- hosts: head
  roles:
    - role: hadoop-hdfs-namenode
      hdfs_namenode_ansible_group: head
      state: started
  tags:
    - hdfs

- hosts: datanodes
  roles:
    - role: hadoop-hdfs-datanode
      hdfs_namenode_ansible_group: head
      state: started
  tags:
    - hdfs

- hosts: spark
  roles:
    - role: spark-standalone-install
      spark_version: 1.6.0
      ssh_key_exchange_ansible_group: spark
      spark_executor_memory: "12G"
      spark_driver_memory: "12G"
      spark_eventlog_enabled: true
      spark_eventlog_dir: "hdfs://{{ hostvars['head']['ansible_nodename'] }}:8020/user/spark/logs"
      spark_history_fs_logdirectory: "hdfs://{{ hostvars['head']['ansible_nodename'] }}:8020/user/spark/logs"

  tags:
    - spark

- hosts: head
  roles:
    - role: spark-standalone-service
      spark_slave_ansible_group: spark-slaves
      state: started
  tags:
    - spark
    - test
