---
- name: Install virtualenv
  apt:
    name: python-virtualenv
    state: latest
  become: yes
  become_user: root

- name: Create virtualenv directory
  file:
    state: directory
    path: "{{ girder_venv }}"
    mode: 0775
    owner: "{{ girder_user }}"
    group: "{{ girder_user }}"
  become: yes
  become_user: root
