---
# tasks file for girder

- command: whoami
  register: role_user_output
  changed_when: false

- name: Ensure girder base directory exists
  file:
    path: "{{ girder_base_path }}"
    state: directory
    group: "{{ role_user_output.stdout }}"
    owner: "{{ role_user_output.stdout }}"
    mode: 0755
  become: yes
  become_user: root


- include: create_virtualenv.yml
  when: girder_venv is defined

- include: install_girder.yml
  when: girder_venv is defined

- include: install_girder.yml
  when: girder_venv is not defined
  become: yes
  become_user: root
