---
# tasks file for girder

- include: create_virtualenv.yml
  when: girder_venv is defined

- include: install_girder.yml
  when: girder_venv is defined

- include: install_girder.yml
  when: girder_venv is not defined
  become: yes
  become_user: root
