---
- fail: msg="girder_path must be defined"
  when: girder_path is not defined

- command: whoami
  register: role_user_output
  changed_when: false

- name: Install minerva base directory
  file:
    path: "{{ minerva_base_path }}"
    state: directory
    group: "{{ role_user_output.stdout }}"
    owner: "{{ role_user_output.stdout }}"
    mode: 0755
  become: yes
  become_user: root

- include: install_minerva.yml
  when: girder_venv is defined

- include: install_minerva.yml
  when: girder_venv is not defined
  become: yes
  become_user: root
