---
install_base_path: "/opt"

girder_version: master
girder_base_path: "{{ install_base_path }}/girder"
girder_venv: "{{ girder_base_path }}/.venv"
girder_path: "{{ girder_base_path }}/{{ girder_version }}"
girder_user: "girder"

cumulus_version: master
cumulus_celery_user: celery

minerva_version: master
