---

  - name: apt | cache | update
    apt: update_cache=yes
    when: do_install|bool

  - name: minerva | deps | install
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - curl
      - g++
      - git
      - libffi-dev
      - make
      - python-dev
      - python-pip
      - libgdal-dev
      - libnetcdf-dev
      - libpng12-dev
      - pkg-config
    when: do_install|bool


  - name: minerva | install root | delete
    file:
        path: "{{ minerva_install_root }}"
        state: absent
    when: remove_install_root|bool

  - name: minerva | data root | delete
    file:
        path: "{{ minerva_data_root }}"
        state: absent
    when: remove_data_root|bool

  - name: minerva | install parent | create
    file:
        path: "{{ minerva_install_parent }}"
        state: directory
    when: do_install|bool

  - name: minerva | data root | create
    file:
        path: "{{ minerva_data_root }}"
        state: directory
        group: "{{ minerva_group }}"
        owner: "{{ minerva_user }}"
        mode: 0755
    when: do_install|bool

  - name: minerva | install root | create
    file:
        path: "{{ minerva_install_root }}"
        state: directory
        group: "{{ minerva_group }}"
        owner: "{{ minerva_user }}"
        mode: 0755
    when: do_install|bool

  - name: minerva | repo | sync
    command: >
        rsync -avz --exclude=.git
        "{{ minerva_git_work_dir }}/"
        "{{ minerva_install_root }}/"
    become: yes
    become_user: "{{ minerva_user }}"
    when: do_install|bool

    # Minerva uses a === syntax in requirements.txt that is not
    # supported by the default version of pip in ubuntu.
  - name: minerva | pip | update
    pip:
      name: pip
      virtualenv: "{{ girder_venv_root }}"
      state: latest
    become: yes
    become_user: "{{ minerva_user }}"
    when: do_install|bool

    # girder-install should take care of this for us,  but for some reason
    # we see a Resource Unavailable' error (probably due to long install times
    # for numpy etc). This is kind of a hack,  but if we install with pip here
    # We don't see the crash and girder-install will skip the installed dependencies
    # Reducing the total time and eliminating the error.
  - name: minerva | install | python dependencies
    pip:
      requirements: "{{minerva_install_root}}/requirements.txt"
      virtualenv: "{{ girder_venv_root }}"
    become: yes
    become_user: "{{ minerva_user }}"
    when: do_install|bool

  - name: minerva | install | plugin
    shell: ". {{ girder_venv_root }}/bin/activate && girder-install plugin -s -f {{ minerva_install_root }}"
    when: do_install|bool
    become: yes
    become_user: "{{ minerva_user }}"
    when: do_install|bool

#  - name: minerva | conf | owner | set
#    file:
#      recurse: yes
#      path: "{{ minerva_install_root }}"
#      group: "{{ minerva_group }}"
#      owner: "{{ minerva_user }}"
#    when: do_install|bool
