- hosts: localhost
  connection: local
  tasks:
    - block:
        - name: Find latest Master AMI
          ec2_ami_find:
            state: available
            sort: creationDate
            sort_order: descending
            ami_tags:
              ec2_pod: "{{ prefix }}"
              ec2_pod_instance_name: "master"
            region: "{{ ec2_region }}"
          register: master_amis

        - name: Register to ec2_master_ami variable
          set_fact:
            ec2_master_ami: "{{ master_amis.results[0]['ami_id'] }}"

      when: ec2_master_ami is not defined

    - block:
        - name: Find latest Node AMI
          ec2_ami_find:
            state: available
            sort: creationDate
            sort_order: descending
            ami_tags:
              ec2_pod: "{{ prefix }}"
              ec2_pod_instance_name: "node"
            region: "{{ ec2_region }}"
          register: node_amis

        - name: Register to ec2_node_ami variable
          set_fact:
            ec2_node_ami: "{{ node_amis.results[0]['ami_id'] }}"

      when: ec2_node_ami is not defined


    - name: Launch master instance
      ec2:
        # Required variables
        instance_type: "{{ ec2_master_instance_type }}"
        image: "{{ ec2_master_ami }}"
        exact_count: 1
        region: "{{ ec2_region }}"

        # Optional variables
        group: "{{ ec2_security_group|default(omit) }}"
        key_name: "{{ ec2_key_name|default(omit) }}"
        instance_profile_name: "{{ ec2_instance_profile_name|default(omit) }}"
        volumes: "{{ ec2_master_volumes|default(omit) }}"
        # Derived or static variables
        instance_tags: "{{ master_tag|combine(ec2_master_additional_tags|default({})) }}"
        count_tag: "{{ master_tag }}"
        wait: true
      register: master

    - name: Launch node instances
      ec2:
        # Required variables
        instance_type: "{{ ec2_node_instance_type }}"
        image: "{{ ec2_node_ami }}"
        exact_count: "{{ ec2_node_count }}"
        region: "{{ ec2_region }}"

        # Optional variables
        group: "{{ ec2_security_group|default(omit) }}"
        key_name: "{{ ec2_key_name|default(omit) }}"
        instance_profile_name: "{{ ec2_instance_profile_name|default(omit) }}"
        volumes: "{{ ec2_node_volumes|default(omit) }}"

        # Derived or static variables
        instance_tags: "{{ node_tag|combine(ec2_node_additional_tags|default({})) }}"
        count_tag: "{{ node_tag }}"
        wait: true
      register: nodes

    - name: Wait for SSH to come up on nodes
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 30
        timeout: 320
        state: started
      with_items: "{{ master.instances + nodes.instances }}"
