- hosts: master
  become: yes
  become_user: root
  handlers:
  roles:
    - role: nginx
      tags: ['nginx']

  post_tasks:
    - name: Install vhosts.
      template:
        src: vhosts.conf
        dest: /etc/nginx/sites-enabled/vhosts.conf
      tags: ['restart', 'restart_nginx', 'nginx']
      become: yes
      become_user: root
      notify: restart nginx


- hosts: master
  become: yes
  become_user: root
  handlers:
  roles:
    - role: graphite
      tags: ['graphite']
      graphite_user: ubuntu
      graphite_secret_key: trustnoone
      graphite_admin_email: chris.kotfila@kitware.com

    - role: grafana
      tags: ['graphana']

    - role: collectd
      tags: ['collectd']

  post_tasks:

    - shell: >-
        service carbon-cache stop;
        service carbon-cache start
      become: yes
      become_user: root
      tags: ['restart', 'restart_graphite']

    - service:
        name: grafana-server
        state: restarted
      tags: ['restart', 'restart_grafana']

    - service:
        name: collectd
        state: restarted
      tags: ['restart', 'restart_collectd']


- hosts: nodes
  become: yes
  become_user: root
  roles:
    - role: collectd
      tags: ['collectd']

  post_tasks:
    - service:
        name: collectd
        state: restarted
      tags: ['restart', 'restart_collectd', 'update_collected_configs']
