- name: Provision the master node
  hosts: master
  roles:
    - { role: generate_users, tags: [ "users", "provision", "provision_users"] }
    - { role: nfs, tags: ["nfs", "provision", "provision_nfs"] }
    - { role: hdfs, tags: ["hdfs", "provisoin", "provision_hdfs"] }

- name: Provision the regular nodes
  hosts: nodes
  roles:
    - { role: generate_users, tags: ["users", "provision", "provision_users"] }
    - { role: nfs, tags: ["nfs", "provision", "provision_nfs"] }
    - { role: hdfs, tags: ["hdfs", "provision", "provision_hdfs"] }


- name: Start services and daemons on master node
  hosts: master
  tasks:
    - name: Start HDFS namenode and datanode daemons
      shell: >-
        {{ hadoop_home }}/sbin/stop-dfs.sh &&
        {{ hadoop_home }}/sbin/start-dfs.sh

      tags: ["hdfs", "restart", "restart_hdfs"]
