- hosts: master
  roles:
    - role: generate_users
      tags:
        - users
    - role: nfs
      tags:
        - nfs
    - role: hdfs
      tags:
        - hdfs

- hosts: nodes
  roles:
    - role: generate_users
      tags:
        - users

    - role: nfs
      tags:
        - nfs

    - role: hdfs
      tags:
        - hdfs
