- name: Provision the master node
  hosts: master
  roles:
    - role: spark-git
      # Tip of master 2016-04-05 09:50:51 EST
      spark_git_version: "branch-2.0"
      tags: ["spark", "provision", "provision_spark"]

- name: Provision the regular nodes
  hosts: nodes
  roles:
    - role: spark-git
      # Tip of master 2016-04-05 09:50:51 EST
      spark_git_version: "branch-2.0"
      tags: ["spark", "provision", "provision_spark"]
