---
- command: whoami
  register: role_user_output
  changed_when: false

- name: Install cumulus base directory
  file:
    path: "{{ cumulus_base_path }}"
    state: directory
    group: "{{ role_user_output.stdout }}"
    owner: "{{ role_user_output.stdout }}"
    mode: 0755
  become: yes
  become_user: root

- name: Install in virtualenv
  include: install_cumulus.yml
  when: girder_venv is defined

- name: Install system-wide
  include: install_cumulus.yml
  when: girder_venv is not defined
  become: yes
  become_user: root
